on:
  push:
    branches: [master]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          echo qbranch hiii
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git status
          git branch
          pwd
          PREFIX="prefix-"
          SRC_ROOT="$(pwd)"
          for FOLDER in foo bar; do
            echo "Doing ${FOLDER}"
            BRANCH="${PREFIX}${FOLDER}"
            git worktree add "../${FOLDER}" "${BRANCH}"
            cd "../${FOLDER}"
            git rm -rf .
            cp -r "${SRC_ROOT}/${FOLDER}" .
            git add .
            git commit -m "Sync from ${{ github.sha }}"
            git push
            cd "${SRC_ROOT}"
          done
            
      
